import {selectCompanies,rankModels,escape as e} from './core.js';
import {b,t,companyCard,modelRows,modelDetail,comparison,checkpoint,timeline,modelScatter,regionCompare} from './render.js';
import {createGlobe} from './globe.js';
export function initObservatory(data){
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
 const language=()=>window.AfflatusI18N?.get?.()||'en';
 const local=v=>v[language()];
 const apply=()=>window.AfflatusI18N?.apply?.();
 const pressed=(selector,key,value)=>$$(selector).forEach(el=>el.setAttribute('aria-pressed',String(el.dataset[key]===String(value))));
 const countText=(count)=>b(`${count} organizations in this selection`,`${count} 个精选机构`);
 const hero=createGlobe($('#ob-hero-globe'),data.companies,{hero:true}),map=createGlobe($('#ob-map-globe'),data.companies);
 let layer='all',country='all',metric='score',modelCountry='all',open=false,selectedModel=data.models[0].id,group='layer',groupValue='all',query='',year='all',eventIndex=-1,gate=1,compareIndex=0,scene=0;
 function updateCompanies(){const rows=selectCompanies(data,{layer,country});$('#ob-company-count').innerHTML=t(countText(rows.length));$('#ob-company-preview').innerHTML=rows.length?rows.slice(0,6).map(c=>companyCard(c,data)).join(''):t(b('No organizations in this combination. Choose another layer or location.','该组合下没有机构，请选择其他层级或位置。'),'p','class="ob-empty"');const selectedCountry=data.regions[country];$('#ob-country-summary').innerHTML=country==='all'?t(b('A shared stack, with concentrated bottlenecks','共同构成产业体系，瓶颈集中于关键环节'),'h3')+t(b('Explore the layers and discover the organizations behind the infrastructure, models and applications.','探索产业层级，认识基础设施、模型与应用背后的机构。'),'p'):t(selectedCountry,'h3')+t(b(rows.map(c=>c.name.en).join(' · '),rows.map(c=>c.name.zh).join(' · ')),'p');map.update(rows,country!=='all'&&rows.length?{longitude:rows[0].lon}:{});apply();}
 $$('[data-layer]').forEach(el=>el.addEventListener('click',()=>{layer=el.dataset.layer;pressed('[data-layer]','layer',layer);updateCompanies();}));$('#ob-country').addEventListener('change',event=>{country=event.target.value;updateCompanies();});$$('[data-map-action]').forEach(el=>el.addEventListener('click',()=>{const a=el.dataset.mapAction;a==='reset'?map.reset():map.zoom(a==='in'?1:-1);}));
 function renderModels(){const rows=rankModels(data.models,{metric,country:modelCountry,open});if(!rows.some(m=>m.id===selectedModel))selectedModel=rows[0]?.id;$('#ob-scatter-container').innerHTML=modelScatter(data,{metric,country:modelCountry,open,selected:selectedModel});$('#ob-model-list').innerHTML=modelRows(data,{metric,country:modelCountry,open,selected:selectedModel});$('#ob-model-detail').innerHTML=modelDetail(data,rows.find(m=>m.id===selectedModel));const units={score:b('AA Intelligence Index · higher is better','AA 能力指数 · 越高越好'),cost:b('USD / AA task · lower is better · shortest bar ranks first','美元 / AA 任务 · 越低越好 · 最短条排在最前'),speed:b('Output tokens / second · higher is better','输出 token / 秒 · 越高越好'),latency:b('Seconds to first chunk · lower is better','首段响应秒数 · 越低越好')};$('#ob-chart-unit').dataset.en=units[metric].en;$('#ob-chart-unit').dataset.zh=units[metric].zh;$('#ob-chart-unit').textContent=local(units[metric]);apply();}
 function chooseModel(id){if(selectedModel===id)return;selectedModel=id;pressed('[data-model]','model',id);pressed('[data-scatter-model]','scatterModel',id);$('#ob-scatter-selection').textContent=data.models.find(m=>m.id===id).name;$('#ob-model-detail').innerHTML=modelDetail(data,data.models.find(m=>m.id===id));apply();}
 $('#ob-model-list').addEventListener('click',event=>{const row=event.target.closest('[data-model]');if(!row)return;chooseModel(row.dataset.model);if(matchMedia('(max-width:620px)').matches)$('#ob-model-detail').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'center'});});$('#ob-model-list').addEventListener('pointerover',event=>{if(event.pointerType==='touch'||matchMedia('(max-width:620px)').matches)return;const row=event.target.closest('[data-model]');if(row)chooseModel(row.dataset.model);});$('#ob-model-list').addEventListener('focusin',event=>{const row=event.target.closest('[data-model]');if(row)chooseModel(row.dataset.model);});

 $('#ob-scatter-container').addEventListener('click',event=>{const point=event.target.closest('[data-scatter-model]');if(point)chooseModel(point.dataset.scatterModel);});$('#ob-scatter-container').addEventListener('focusin',event=>{const point=event.target.closest('[data-scatter-model]');if(point)chooseModel(point.dataset.scatterModel);});$('#ob-scatter-container').addEventListener('pointerover',event=>{if(event.pointerType==='touch')return;const point=event.target.closest('[data-scatter-model]');if(point)chooseModel(point.dataset.scatterModel);});$('#ob-scatter-container').addEventListener('keydown',event=>{if(event.key!=='Enter'&&event.key!==' ')return;const point=event.target.closest('[data-scatter-model]');if(point){event.preventDefault();chooseModel(point.dataset.scatterModel);}});
 $$('[data-metric]').forEach(el=>el.addEventListener('click',()=>{metric=el.dataset.metric;pressed('[data-metric]','metric',metric);renderModels();}));$('#ob-model-country').addEventListener('change',event=>{modelCountry=event.target.value;renderModels();});$('#ob-open-only').addEventListener('change',event=>{open=event.target.checked;renderModels();});
 function updateComparison(){ $('#ob-compare-metric').value=String(compareIndex);$('#ob-comparison-body').innerHTML=comparison(data,compareIndex);apply();}$('#ob-compare-metric').addEventListener('change',event=>{compareIndex=Number(event.target.value);updateComparison();});$$('[data-compare-step]').forEach(el=>el.addEventListener('click',()=>{compareIndex=(compareIndex+Number(el.dataset.compareStep)+data.comparison.length)%data.comparison.length;updateComparison();}));
 $$('[data-year]').forEach(el=>el.addEventListener('click',()=>{year=el.dataset.year;eventIndex=-1;pressed('[data-year]','year',year);$('#ob-timeline').innerHTML=timeline(data,year);apply();}));$$('[data-event-step]').forEach(el=>el.addEventListener('click',()=>{const entries=$$('#ob-timeline details');if(!entries.length)return;const current=entries.findIndex(el=>el.open);eventIndex=((current<0?(Number(el.dataset.eventStep)>0?-1:0):current)+Number(el.dataset.eventStep)+entries.length)%entries.length;entries.forEach((el,i)=>{el.open=i===eventIndex;});entries[eventIndex].scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});}));
 $$('[data-gate]').forEach(el=>el.addEventListener('click',()=>{gate=Number(el.dataset.gate);pressed('[data-gate]','gate',gate);$('#ob-gate-detail').innerHTML=checkpoint(data,gate);apply();}));

 const regionIds=Object.keys(data.regions).filter(k=>data.companies.some(c=>c.country===k));let leftRegion='US',rightRegion='CN';
 function drawSlopes(highlight){const chart=$('#ob-region-chart'),canvas=$('#ob-slope-lines'),columns=$$('.ob-region-columns ol');if(!canvas||columns.length!==2)return;const box=chart.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=box.width*dpr;canvas.height=box.height*dpr;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.setTransform(dpr,0,0,dpr,0,0);for(const row of columns[0].children){const other=[...columns[1].children].find(el=>el.dataset.compareLayer===row.dataset.compareLayer);if(!other)continue;const a=row.getBoundingClientRect(),b=other.getBoundingClientRect(),active=row.dataset.compareLayer===highlight;ctx.beginPath();ctx.moveTo(a.right-box.left+8,a.top-box.top+a.height/2);ctx.lineTo(b.left-box.left-8,b.top-box.top+b.height/2);ctx.strokeStyle=active?'#668543':'#d0ccbf';ctx.lineWidth=active?2:1;ctx.stroke();}chart.querySelectorAll('[data-compare-layer]').forEach(row=>row.classList.toggle('is-traced',row.dataset.compareLayer===highlight));}
 function renderRegions(){ $('#ob-region-left').value=leftRegion;$('#ob-region-right').value=rightRegion;$('#ob-region-chart').innerHTML=regionCompare(data,leftRegion,rightRegion);apply();drawSlopes();}
 ['left','right'].forEach(side=>$('#ob-region-'+side).addEventListener('change',event=>{if(side==='left')leftRegion=event.target.value;else rightRegion=event.target.value;renderRegions();}));$$('[data-region-step]').forEach(el=>el.addEventListener('click',()=>{const side=el.dataset.side,current=side==='left'?leftRegion:rightRegion,value=regionIds[(regionIds.indexOf(current)+Number(el.dataset.regionStep)+regionIds.length)%regionIds.length];if(side==='left')leftRegion=value;else rightRegion=value;renderRegions();}));$('#ob-region-chart').addEventListener('pointerover',event=>{const row=event.target.closest('[data-compare-layer]');if(row)drawSlopes(row.dataset.compareLayer);});$('#ob-region-chart').addEventListener('focusin',event=>{const row=event.target.closest('[data-compare-layer]');if(row)drawSlopes(row.dataset.compareLayer);});const slopeResize=new ResizeObserver(()=>drawSlopes());slopeResize.observe($('#ob-region-chart'));drawSlopes();
 const dialog=$('#ob-directory');
 function renderDirectoryGroups(){const items=group==='layer'?data.layers.map(l=>[l.id,l.name]):Object.entries(data.regions).filter(([id])=>data.companies.some(c=>c.country===id));$('#ob-directory-groups').innerHTML=[[ 'all',b('All','全部')],...items].map(([id,name])=>t(name,'button',`type="button" data-directory-group="${e(id)}" aria-pressed="${id===groupValue}"`)).join('');}
 function renderDirectory(){const rows=selectCompanies(data,{query,layer:group==='layer'?groupValue:'all',country:group==='country'?groupValue:'all'});$('#ob-directory-count').innerHTML=t(countText(rows.length));$('#ob-directory-results').innerHTML=rows.length?rows.map(c=>companyCard(c,data)).join(''):t(b('No matches. Try a company, industry or place; or clear the selected group.','没有匹配结果。试试公司、行业或地点，或清除当前分组筛选。'),'p','class="ob-empty"');apply();}
 $$('[data-open-directory]').forEach(el=>el.addEventListener('click',()=>{group='layer';groupValue=layer;query='';$('#ob-company-search').value='';pressed('[data-group]','group',group);renderDirectoryGroups();renderDirectory();dialog.showModal();}));$$('[data-close-directory]').forEach(el=>el.addEventListener('click',()=>dialog.close()));dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();});$$('[data-group]').forEach(el=>el.addEventListener('click',()=>{group=el.dataset.group;groupValue='all';pressed('[data-group]','group',group);renderDirectoryGroups();renderDirectory();}));$('#ob-directory-groups').addEventListener('click',event=>{const el=event.target.closest('[data-directory-group]');if(!el)return;groupValue=el.dataset.directoryGroup;pressed('[data-directory-group]','directoryGroup',groupValue);renderDirectory();});$('#ob-company-search').addEventListener('input',event=>{query=event.target.value;renderDirectory();});
 $$('[data-source-kind]').forEach(el=>el.addEventListener('click',()=>{const kind=el.dataset.sourceKind;pressed('[data-source-kind]','sourceKind',kind);$$('[data-source-record]').forEach(row=>{row.hidden=kind!=='all'&&row.dataset.sourceRecord!==kind;});}));
 $('#ob-copy-citation').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#ob-citation').textContent);$('#ob-copy-status').textContent=local(b('Citation copied.','引用已复制。'));}catch{const details=$('#ob-citation').closest('details');details.open=true;const range=document.createRange();range.selectNodeContents($('#ob-citation'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);$('#ob-copy-status').textContent=local(b('Select and copy the citation below.','请复制下方已选中的引用。'));}});
 const scenes=[{label:b('CAPABILITY · CAPITAL · CONTROL','能力 · 资本 · 控制'),body:b('A stronger model is only the beginning. Compute, distribution and trust determine what follows.','更强的模型只是起点。算力、分发与信任，决定接下来会发生什么。'),lon:-75,color:'#e3c168'},{label:b('A GLOBAL INDUSTRY','一条全球产业链'),body:b('The frontier spans laboratories, chip fabs, power grids and the tools we use every day.','智能前沿穿越实验室、晶圆厂与电网，最终进入我们每天使用的工具。'),lon:95,color:'#c4d39a'},{label:b('THE NEXT CAPABILITY GATE','下一道能力关卡'),body:b('Agents can already do useful work. Reliable general intelligence still has to be demonstrated.','智能体已经能够完成有用的工作。可靠的通用智能，仍有待证明。'),lon:10,color:'#a9c4d6'}];
 function setScene(index){scene=index;pressed('[data-scene]','scene',index);$('#ob-scene-label').innerHTML=t(scenes[index].label);$('#ob-scene-label').style.background=scenes[index].color;$('#ob-scene-text').dataset.en=scenes[index].body.en;$('#ob-scene-text').dataset.zh=scenes[index].body.zh;$('#ob-scene-text').textContent=local(scenes[index].body);hero.update(data.companies,{longitude:scenes[index].lon});apply();}$$('[data-scene]').forEach(el=>el.addEventListener('click',()=>setScene(Number(el.dataset.scene))));
 let scrollPending=false;function scroll(){if(scrollPending)return;scrollPending=true;requestAnimationFrame(()=>{scrollPending=false;const story=$('.ob-story'),rect=story.getBoundingClientRect(),travel=story.offsetHeight-window.innerHeight+68,progress=Math.max(0,Math.min(.999,(68-rect.top)/Math.max(travel,1)));if(rect.bottom>68&&rect.top<window.innerHeight&&!matchMedia('(prefers-reduced-motion:reduce)').matches){const next=Math.floor(progress*3);if(next!==scene)setScene(next);}});}window.addEventListener('scroll',scroll,{passive:true});
 const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){$$('.ob-chapter-nav a').forEach(a=>{if(a.hash===`#${entry.target.id}`)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}},{rootMargin:'-140px 0px -55% 0px',threshold:0});$$('.ob-chapter[id]').filter(el=>el.id!=='sources').forEach(el=>observer.observe(el));
 window.addEventListener('afflatus-lang',()=>{if(dialog.open)renderDirectory();$('#ob-copy-status').textContent='';});window.addEventListener('pagehide',event=>{if(event.persisted)return;observer.disconnect();slopeResize.disconnect();hero.dispose();map.dispose();window.removeEventListener('scroll',scroll);});
 $('#ob-company-count').innerHTML=t(countText(data.companies.length));apply();
}
