import {b,t,sourceLink} from './render.js';
import {escape as e} from './core.js';
const tx=(en,zh,tag='p',attrs='')=>t(b(en,zh),tag,attrs);

// A scenario based on a dated reported ratio, not a new measurement of plan caps.
export function utilizedValueRatio(claude,openai,base=5){
 if(![claude,openai,base].every(Number.isFinite)||claude<0||claude>100||openai<=0||openai>100||base<0)return null;
 return base*claude/openai;
}
export function workloadCost(pricing,{prompt=25000,output=1000,cache=80}={}){
 if(![prompt,output,cache].every(Number.isFinite)||prompt<0||output<0||cache<0||cache>100)throw new RangeError('Invalid workload');
 const rates=prompt>pricing.threshold?pricing.long:pricing.short;
 const cost=p=>(prompt*((1-cache/100)*p.input+cache/100*p.read)+output*p.output)/1e6;
 return {long:prompt>pricing.threshold,haiku:cost(rates),previous:cost(pricing.previous),sonnet:cost(pricing.sonnet)};
}
export function haikuEffort(data,id='high'){
 const row=data.haiku.efforts.find(v=>v.id===id);
 return `<div class="ob-effort-reading"><div><span>${e(id)}</span>${tx('AA index','AA 指数','small')}<strong>${row.score}</strong></div><div>${tx('USD / AA task','美元 / AA 任务','small')}<strong>$${row.cost.toFixed(2)}</strong></div><div>${tx('First chunk · seconds','首段响应 · 秒','small')}<strong>${row.latency.toFixed(2)}</strong></div><div>${tx('Output tokens / s','输出 token / 秒','small')}<strong>${row.speed}</strong></div></div>${tx('Changing effort here compares measured configurations; the main family ranking retains max. Output speed measures generation after the first chunk.','此处切换测量档位；主榜的系列代表仍使用 max。输出速度衡量首段响应之后的生成过程。','p','class="ob-caption"')}${tx('View this configuration ↗','查看该配置 ↗','a',`href="${e(row.url)}" target="_blank" rel="noopener noreferrer" class="ob-source"`)}`;
}
export function haikuSpotlight(data){
 return `<article class="ob-haiku-launch" id="haiku-launch"><div class="ob-haiku-title"><p class="ob-eyebrow">${tx('NEW · 7 OCTOBER 2026','新发布 · 2026 年 10 月 7 日','span')}</p><h3>Claude Haiku 5.5</h3>${tx('Intelligence finds a smaller form.','智能，找到更轻盈的形态。','p','class="ob-launch-lede"')}${tx('A fast helper deserves its own settings. Compare the wait, cost and capability before choosing how much thinking a task needs.','快速助手也需要合适的档位。比较等待、成本与能力，让任务决定需要多少思考。')}${sourceLink(data,'haiku-release',true)}${tx('Read our analysis ↓','阅读本站分析 ↓','a','href="#subscription-economics" class="ob-source"')}</div><div class="ob-haiku-efforts"><div class="ob-effort-buttons" role="group" aria-label="Haiku effort" data-aria-en="Haiku effort" data-aria-zh="Haiku 推理档位">${data.haiku.efforts.map(row=>`<button type="button" data-haiku-effort="${row.id}" aria-pressed="${row.id==='high'}"><span>${row.id}</span><span class="ob-effort-meter" aria-hidden="true"><i style="width:${row.score/50*100}%"></i></span></button>`).join('')}</div><div id="ob-haiku-effort-detail" aria-live="polite">${haikuEffort(data)}</div></div></article>`;
}
export function utilizationReading(claude=60,openai=80){
 const ratio=utilizedValueRatio(claude,openai);
 return `<strong>${ratio==null?'—':ratio.toFixed(2)+'×'}</strong>${tx('Utilization-adjusted API-equivalent ratio','利用率调整后的 API 等值倍数','span')}<div class="ob-utilization-track" aria-hidden="true"><i style="width:${Math.min((ratio||0)/5*100,100)}%"></i></div>${tx(ratio==null?'Set OpenAI utilization above zero to compare.':`5 × ${claude}% ÷ ${openai}% = ${ratio.toFixed(2)}×. A scenario, not measured savings.`,ratio==null?'将 OpenAI 利用率设为大于零，即可比较。':`5 × ${claude}% ÷ ${openai}% = ${ratio.toFixed(2)} 倍。情景计算，不是实测节省额。`,'p','class="ob-caption"')}`;
}
export function workloadReading(data,options){
 const r=workloadCost(data.haiku.pricing,options),rows=[['Haiku 5.5',r.haiku],['Haiku 4.5',r.previous],['Sonnet 5.5',r.sonnet]],max=Math.max(...rows.map(row=>row[1]));
 return `<div class="ob-workload-bars">${rows.map(([name,cost])=>`<div><span>${name}</span><span class="ob-workload-track" aria-hidden="true"><i style="width:${max?cost/max*100:0}%"></i></span><strong>$${cost.toFixed(5)}</strong></div>`).join('')}</div>${tx(`Haiku 5.5 price tier: ${r.long?'over':'up to'} 100k prompt tokens. USD per modeled request.`, `Haiku 5.5 价格档：提示词${r.long?'超过':'不超过'} 100k token。单位：美元 / 情景请求。`,'p','class="ob-caption"')}`;
}
export function economicsAnalysis(data){
 return `<div class="ob-prose ob-original-intro">${tx('AFFLATUS ORIGINAL ANALYSIS','AFFLATUS 原创分析','p','class="ob-eyebrow"')}${tx('The scarce resource is a finished task.','真正稀缺的，是完成的任务。','h3')}${tx('A subscription purchases access to a changing pool of compute. The useful question is how much of that access becomes work you can accept. We separate the reported allowance, the fraction you can use, and the quality you verify.','订阅购买的是一池会变化的算力使用权。更有意义的问题是：其中多少，最终变成你可以验收的工作。我们把报道中的额度、实际可用的比例与经过验证的质量分开讨论。')}${tx('Evidence boundary: we read the publicly accessible SemiAnalysis article. Its paid Tokenomics Dashboard and the locked third-party-plan section were not available. The 5 October results remain attributed; we did not retest subscription limits.','证据边界：已阅读 SemiAnalysis 可公开访问的正文；付费 Tokenomics 仪表盘与被锁定的第三方套餐部分未能读取。10 月 5 日结果仍归于原作者，本站未重新实测订阅额度。','p','class="ob-caption"')}</div>
<div class="ob-wide ob-analysis-grid"><article>${tx('01 / The denominator changes the story','01 / 分母，改变故事','p','class="ob-eyebrow"')}${tx('An API dollar is a reference price.','API 美元，是一种参照价格。','h3')}${tx('API-equivalent value multiplies usable tokens by the API list price. If that price halves while token allowance stays fixed, the reported dollar value halves too. Access has not changed. Read token volume and task acceptance alongside the headline ratio; an expensive API can inflate the apparent subsidy.','API 等值用可用 token 乘以 API 标价。若标价减半而 token 额度不变，美元等值也会减半，使用权却没有变化。因此，解读倍数时应同时查看 token 量与任务验收结果；较贵的 API 可能放大表观补贴。')}${sourceLink(data,'semianalysis-subscriptions',true)}</article><article>${tx('02 / Rhythm is part of the product','02 / 工作节奏，是产品的一部分','p','class="ob-eyebrow"')}${tx('An allowance must be reachable.','额度，要能被用到。','h3')}${tx('A large weekly allowance can still be a poor fit for a compressed deadline. Model-specific caps, reset windows and bursty work affect utilization. A fair comparison should record the fraction actually consumed during your working hours, rather than assume every buyer exhausts the plan.','较大的周额度，仍可能不适合集中赶工。模型子上限、重置窗口与突发任务都会影响利用率。公平比较应记录你在实际工作时间内用掉的比例，而不是假设每位用户都会把套餐耗尽。')}${tx('At a 5× reference ratio, the utilization break-even is Claude utilization = one fifth of OpenAI utilization. That is algebra under the reported premise, not a purchasing verdict.','以 5 倍为参照，利用率收支平衡点是：Claude 利用率等于 OpenAI 的五分之一。这是报道前提下的代数结果，不是购买结论。','p','class="ob-caption"')}</article></div>
<div class="ob-wide ob-economics-lab"><div>${tx('Make the assumption visible','让假设可见','h3')}${tx('Start from SemiAnalysis’s approximate 5× daily-driver ratio. Move the utilization assumptions to see how much of the nominal advantage you can reach. Quality and task mix are held outside this calculation.','以 SemiAnalysis 日常主力模型约 5 倍的比值为参照。调整利用率假设，观察名义优势能兑现多少。本计算不计入质量与任务组合差异。','p','class="ob-caption"')}<label for="ob-claude-utilization">${tx('Claude allowance used','Claude 额度利用率','span')}<output for="ob-claude-utilization" id="ob-claude-utilization-value">60%</output></label><input id="ob-claude-utilization" type="range" min="0" max="100" value="60" step="5"><label for="ob-openai-utilization">${tx('OpenAI allowance used','OpenAI 额度利用率','span')}<output for="ob-openai-utilization" id="ob-openai-utilization-value">80%</output></label><input id="ob-openai-utilization" type="range" min="0" max="100" value="80" step="5"><button type="button" class="ob-button" id="ob-reset-utilization">${tx('Reset assumptions','重置假设','span')}</button></div><div id="ob-utilization-result" class="ob-utilization-result" aria-live="polite">${utilizationReading()}</div></div>
<div class="ob-wide ob-analysis-grid"><article>${tx('03 / Haiku changes the division of labor','03 / Haiku 改变分工','p','class="ob-eyebrow"')}${tx('Buy precision where it matters.','把更深的思考，留给关键处。','h3')}${tx('Our architecture thesis: let a small model extract, classify and summarize; let a stronger model plan, resolve ambiguity and review. Escalation needs an explicit trigger such as missing evidence or a failed check. Savings survive only if verification and retries cost less than the work delegated.','本站的架构判断：小模型负责提取、分类与摘要，更强的模型负责规划、消解歧义和复核。升级处理需要明确触发条件，例如证据不足或检查失败。只有验证与重试成本低于委派所节省的成本，这种分工才成立。')}${tx('Measure cost per accepted result = total model, tool, retry and review cost ÷ accepted results. The AA index helps select candidates; your own acceptance tests decide deployment.','应衡量每个验收结果的成本 = 模型、工具、重试与复核总成本 ÷ 验收结果数。AA 指数帮助选择候选，自己的验收测试决定能否部署。','p','class="ob-caption"')}</article><article>${tx('04 / Efficiency has several frontiers','04 / 效率，有多条前沿','p','class="ob-eyebrow"')}${tx('Choose the bottleneck first.','先找到工作中的瓶颈。','h3')}${tx('In this shortlist, MiMo scores 46 at $0.13 per AA task; Haiku max scores 43 at $0.21. Haiku’s case rests on the wider system: effort control, output speed, tool fit and operational continuity. A cost–capability plot cannot decide interactive responsiveness or verified work quality.','在本精选中，MiMo 为 46 分、每 AA 任务 $0.13；Haiku max 为 43 分、$0.21。Haiku 的价值要放进更大的系统理解：档位控制、输出速度、工具适配与运维连续性。成本—能力图不能单独决定交互响应或经验证的工作质量。')}${sourceLink(data,'aa',true)}${tx('A small model can generate quickly yet think for a long time at max. Compare first-chunk delay separately from tokens per second.','小模型可以生成很快，同时在 max 档思考很久。首段等待应与每秒 token 数单独比较。','p','class="ob-caption"')}</article></div>
<div class="ob-wide ob-workload-lab"><div>${tx('The shape of a request changes its bill','请求的形状，会改变账单','h3')}${tx('A fixed-token API scenario using the official price table. Adjust total prompt length and cache hits; output stays at 1,000 tokens. This is independent of subscription caps and of the AA task mix.','依据官方价格表的固定 token API 情景。调整提示词总长度与缓存命中率，输出固定为 1,000 token。它独立于订阅额度，也不同于 AA 任务组合。','p','class="ob-caption"')}</div><div class="ob-workload-controls"><label for="ob-prompt-tokens">${tx('Total prompt tokens','提示词总 token','span')}<output for="ob-prompt-tokens" id="ob-prompt-value">25,000</output></label><input id="ob-prompt-tokens" type="range" min="1000" max="200000" step="1000" value="25000"><label for="ob-cache-hit">${tx('Already cached prompt share','已缓存提示词比例','span')}<output for="ob-cache-hit" id="ob-cache-value">80%</output></label><input id="ob-cache-hit" type="range" min="0" max="100" step="5" value="80"></div><div id="ob-workload-result" aria-live="polite">${workloadReading(data)}</div>${tx('Cost = fresh input × input rate + cached input × read rate + output × output rate, divided by 1M. Above 100k, the higher Haiku rate applies to the whole request. No cache writes, tools, retries, batch discounts or tokenizer differences are modeled. Equal token counts do not imply equal task quality.','成本 =（新输入 × 输入单价 + 缓存输入 × 读取单价 + 输出 × 输出单价）÷ 100 万。超过 100k 时，Haiku 整个请求适用高价档。未计入缓存写入、工具、重试、批处理折扣或 tokenizer 差异。相同 token 数不意味着相同任务质量。','p','class="ob-caption"')}${sourceLink(data,'haiku-release',true)}</div>
<div class="ob-prose ob-original-close">${tx('05 / A bridge from subscribers to builders','05 / 从订阅用户，到应用构建者','p','class="ob-eyebrow"')}${tx('The next moat may be a workflow.','下一条护城河，可能是一套工作流。','h3')}${tx('Anthropic announced monthly API credits for Max and Team alongside this release. Our inference is that a subscription can become a route into API applications: the user who learns to compose and verify a workflow may later pay for sustained usage. Credits invite experimentation; durable margins still depend on retention, utilization and the full cost to serve.','Anthropic 随发布宣布为 Max 与 Team 提供每月 API 抵用额。本站推断：订阅可以成为进入 API 应用的通道，学会组合与验证工作流的人，可能继续为持续用量付费。抵用额鼓励试验；持久利润仍取决于留存、利用率与完整服务成本。')}${tx('This is a testable business thesis, not a revenue forecast. Watch accepted-task cost, repeat API use after credits, escalation rate and paid retention. Keep the October 5 subscription tests separate from the October 7 product changes.','这是可以检验的商业判断，不是收入预测。应追踪验收任务成本、抵用额之后的重复 API 使用、升级处理率与付费留存。10 月 5 日订阅测试，需与 10 月 7 日产品变化分开。','p','class="ob-caption"')}${sourceLink(data,'haiku-release',true)}</div>`;
}
export function initEconomics(data){
 const $=s=>document.querySelector(s),apply=()=>window.AfflatusI18N?.apply?.();
 document.querySelectorAll('[data-haiku-effort]').forEach(el=>el.addEventListener('click',()=>{document.querySelectorAll('[data-haiku-effort]').forEach(v=>v.setAttribute('aria-pressed',String(v===el)));$('#ob-haiku-effort-detail').innerHTML=haikuEffort(data,el.dataset.haikuEffort);apply();}));
 function utilization(){const a=Number($('#ob-claude-utilization').value),o=Number($('#ob-openai-utilization').value);$('#ob-claude-utilization-value').textContent=a+'%';$('#ob-openai-utilization-value').textContent=o+'%';$('#ob-utilization-result').innerHTML=utilizationReading(a,o);apply();}
 ['#ob-claude-utilization','#ob-openai-utilization'].forEach(id=>$(id).addEventListener('input',utilization));$('#ob-reset-utilization').addEventListener('click',()=>{$('#ob-claude-utilization').value=60;$('#ob-openai-utilization').value=80;utilization();});
 function workload(){const prompt=Number($('#ob-prompt-tokens').value),cache=Number($('#ob-cache-hit').value);$('#ob-prompt-value').textContent=prompt.toLocaleString('en-AU');$('#ob-cache-value').textContent=cache+'%';$('#ob-workload-result').innerHTML=workloadReading(data,{prompt,cache,output:1000});apply();}
 ['#ob-prompt-tokens','#ob-cache-hit'].forEach(id=>$(id).addEventListener('input',workload));
}
