import {b,t,sourceLink} from './render.js';
import {escape as e} from './core.js';
const tx=(en,zh,tag='p',attrs='')=>t(b(en,zh),tag,attrs);
const btn=(en,zh,attrs='')=>tx(en,zh,'button',`type="button" ${attrs}`);
export function researchBars(rows,tone='green'){
 return `<ol class="ob-research-bars ${tone}">${rows.map((r,i)=>`<li><details><summary><span class="ob-rank">${String(i+1).padStart(2,'0')}</span><span class="ob-research-track"><span style="--bar:${r.value / Math.max(...rows.map(v=>v.value)) * 100}%" aria-hidden="true"></span>${t(r.label)}</span><strong>${r.value}%</strong><span class="ob-plus" aria-hidden="true">+</span></summary><div class="ob-research-body">${t(r.note,'p')}</div></details></li>`).join('')}</ol>`;
}
export function researchWall(data,source='all',query='',topic='all'){
 const rows=data.research.cards.filter(c=>(source==='all'||c.source===source)&&(topic==='all'||c.topic===topic)&&`${c.title.en} ${c.title.zh} ${c.body.en} ${c.body.zh}`.toLowerCase().includes(query.trim().toLowerCase()));
 return rows.length?rows.map(c=>`<article class="ob-research-card"><p class="ob-eyebrow">${c.source==='a16z-apps'?'a16z':'SemiAnalysis'} · 2026-10-05</p>${t(c.title,'h3')}${t(c.body,'p')}${sourceLink(data,c.source,true)}</article>`).join(''):tx('No matching evidence. Clear the search or choose another source.','没有匹配证据。请清空搜索或更换来源。','p','class="ob-empty"');
}
export function subscriptionComparison(data,key='daily'){
 const c=data.research.comparisons.find(c=>c.id===key);
 return `${t(c.title,'h3')}<div class="ob-value-comparison">${c.values.map(v=>`<div>${t(v.label)}<strong>${e(v.display)}</strong><div class="ob-value-track" aria-hidden="true"><span style="--bar:${v.bar}%"></span></div></div>`).join('')}</div>${t(c.note,'p','class="ob-caption"')}`;
}
export function researchChapters(data){
 const r=data.research;
 return `<section id="consumer-ai" class="ob-chapter"><div class="ob-prose"><div class="ob-chapter-kicker"><span>07 / 08</span>${tx('CONSUMER AI','消费 AI','span')}</div>${tx('Who uses AI. Who pays for it.','谁在使用 AI，谁在为它付费。','h2')}${tx('Traffic, spending and distribution reveal different markets.','流量、支出与分发，揭示不同的市场。')}${sourceLink(data,'a16z-apps')}${tx('Olivia Moore · 5 October 2026','Olivia Moore · 2026 年 10 月 5 日','p','class="ob-caption"')}<div class="ob-stat-line"><div><strong>4.5%</strong>${tx('paid personal subscriptions¹','个人付费订阅¹','span')}</div><div><strong>$25</strong>${tx('median payer / month','付费者月支出中位数','span')}</div><div><strong>$903</strong>${tx('top 1% / month','前 1% 月支出','span')}</div></div></div>
<div class="ob-wide ob-research-chart">${tx('Spending concentration','支出集中度','h3')}${tx('US consumer panel · August 2026 · bars scaled to group maximum','美国消费者样本 · 2026 年 8 月 · 条长按组内最大值缩放','p','class="ob-caption"')}${researchBars(r.spending)}<div class="ob-spend-dots" aria-hidden="true">${Array.from({length:100},(_,i)=>`<i class="${i<20?'is-top':''}"></i>`).join('')}</div>${tx('100 dots = all observed spending; 20 shaded dots ≈ the top 1% share.','100 点表示全部观测支出；20 个深色点约对应前 1% 的份额。','p','class="ob-caption"')}</div>
<div class="ob-wide ob-research-chart">${tx('How products monetize','产品如何变现','h3')}${researchBars(r.monetization,'blue')}${tx('44 AI-native web products; overlapping models. ¹ChatGPT, Gemini or Claude. Panel spending is not company revenue.','44 个 AI 原生网页产品；模式可重叠。¹ChatGPT、Gemini 或 Claude。样本支出不等于公司收入。','p','class="ob-caption"')}</div></section>
<section id="subscription-economics" class="ob-chapter"><div class="ob-prose"><div class="ob-chapter-kicker"><span>08 / 08</span>${tx('SUBSCRIPTION ECONOMICS','订阅经济','span')}</div>${tx('The price is only the beginning.','价格，只是起点。','h2')}${tx('Compare a plan, model and workload together.','套餐、模型与工作负载，应一起比较。')}${sourceLink(data,'semianalysis-subscriptions')}${tx('Andrew Megalaa, Max Kan & Dylan Patel · 5 October 2026','Andrew Megalaa、Max Kan 与 Dylan Patel · 2026 年 10 月 5 日','p','class="ob-caption"')}</div><div class="ob-wide ob-subscription-panel"><div class="ob-comparison-heading">${tx('Compare the reported tests','查看报道中的测试','h3')}<label for="ob-subscription-case">${tx('Test case','测试场景','span')}</label><select id="ob-subscription-case">${r.comparisons.map(c=>t(c.label,'option',`value="${c.id}"`)).join('')}</select></div><div id="ob-subscription-comparison" aria-live="polite">${subscriptionComparison(data)}</div>${tx('API-equivalent value ≠ quality or guaranteed savings. Dated agentic-workload estimates; limits can change.','API 等值不等于质量或保证节省额。基于当时智能体工作负载的估算；额度可能变动。','p','class="ob-caption"')}<details class="ob-research-method"><summary>${tx('Measurement method','测量方法','span')}</summary>${tx('Isolate input, cache write, cache read and output; observe meter increments; apply weekly caps and API prices.','分别测量输入、缓存写入、缓存读取与输出；观察额度变化，结合周上限与 API 价格。')}${sourceLink(data,'semianalysis-subscriptions',true)}</details></div>
<div class="ob-prose ob-research-bridge">${tx('Read across the evidence','串联证据','h3')}${tx('Our reading: adoption, willingness to pay and cost to serve are separate questions. Use the evidence wall to compare the two lenses.','本站解读：使用规模、付费意愿与服务成本是三个不同问题。通过证据墙比较这两个视角。')}<button type="button" class="ob-button ob-button-dark" data-open-research>${tx('Explore the evidence ↗','浏览证据 ↗','span')}</button></div></section>
<dialog id="ob-research-wall" aria-labelledby="ob-research-title"><div class="ob-dialog-top"><div>${tx('THE EVIDENCE WALL','证据墙','p','class="ob-eyebrow"')}${tx('Two lenses on the AI market','AI 市场的两个视角','h2','id="ob-research-title"')}</div><div>${btn('↗','↗','data-expand-research aria-label="Expand evidence wall" data-aria-en="Expand evidence wall" data-aria-zh="展开证据墙" aria-pressed="false"')}${btn('×','×','data-close-research aria-label="Close evidence wall" data-aria-en="Close evidence wall" data-aria-zh="关闭证据墙"')}</div></div><div class="ob-dialog-controls"><label class="ob-search-label" for="ob-research-search">${tx('Search evidence','搜索证据','span')}<input type="search" id="ob-research-search" placeholder="Search findings…" data-en-ph="Search findings…" data-zh-ph="搜索发现…"></label><div class="ob-pills" role="group" aria-label="Evidence source" data-aria-en="Evidence source" data-aria-zh="证据来源">${[['all','All','全部'],['a16z-apps','a16z','a16z'],['semianalysis-subscriptions','SemiAnalysis','SemiAnalysis']].map(([id,en,zh])=>btn(en,zh,`data-research-source="${id}" aria-pressed="${id==='all'}"`)).join('')}</div><label for="ob-research-topic">${tx("Topic","主题","span")}</label><select id="ob-research-topic">${[["all","All topics","全部主题"],["adoption","Adoption","使用"],["product","Products","产品"],["value","Value & limits","价值与额度"]].map(([id,en,zh])=>tx(en,zh,"option",`value="${id}"`)).join('')}</select></div><p id="ob-research-count" class="ob-caption" role="status">${r.cards.length}</p><div class="ob-research-wall-layout"><aside class="ob-research-sidebar" aria-label="Topic filters" data-aria-en="Topic filters" data-aria-zh="主题筛选">${[['all','All topics','全部主题'],['adoption','Adoption','使用'],['product','Products','产品'],['value','Value & limits','价值与额度']].map(([id,en,zh])=>btn(en,zh,`data-wall-topic="${id}" aria-pressed="${id==='all'}"`)).join('')}</aside><div id="ob-research-results" class="ob-research-grid">${researchWall(data)}</div></div></dialog>`;
}
export function initResearch(data){
 document.querySelectorAll('.ob-research-bars details').forEach(el=>{el.addEventListener('pointerenter',event=>{if(event.pointerType==='mouse'&&matchMedia('(min-width:769px)').matches)el.open=true;});});
 const wall=document.querySelector('#ob-research-wall');let source='all',query='',topic='all';
 const apply=()=>window.AfflatusI18N?.apply?.();
 function render(){wall.querySelectorAll('[data-wall-topic]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.wallTopic===topic)));document.querySelector('#ob-research-topic').value=topic;const html=researchWall(data,source,query,topic);document.querySelector('#ob-research-results').innerHTML=html;const count=wall.querySelectorAll('.ob-research-card').length;document.querySelector('#ob-research-count').innerHTML=tx(`${count} evidence cards`,`${count} 条证据`,'span');apply();}
 document.querySelector('[data-open-research]').addEventListener('click',()=>{render();wall.showModal();});
 wall.querySelectorAll('[data-wall-topic]').forEach(el=>el.addEventListener('click',()=>{topic=el.dataset.wallTopic;render();}));
 document.querySelector('#ob-research-topic').addEventListener('change',event=>{topic=event.target.value;render();});
 document.querySelector('[data-expand-research]').addEventListener('click',event=>{const expanded=wall.classList.toggle('is-expanded');event.currentTarget.setAttribute('aria-pressed',String(expanded));});
 document.querySelector('[data-close-research]').addEventListener('click',()=>wall.close());
 wall.addEventListener('click',event=>{if(event.target!==wall)return;const r=wall.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)wall.close();});
 document.querySelector('#ob-research-search').addEventListener('input',event=>{query=event.target.value;render();});
 wall.querySelectorAll('[data-research-source]').forEach(el=>el.addEventListener('click',()=>{source=el.dataset.researchSource;wall.querySelectorAll('[data-research-source]').forEach(v=>v.setAttribute('aria-pressed',String(v===el)));render();}));
 document.querySelector('#ob-subscription-case').addEventListener('change',event=>{document.querySelector('#ob-subscription-comparison').innerHTML=subscriptionComparison(data,event.target.value);apply();});
 window.addEventListener('afflatus-lang',()=>{if(wall.open)render();});
}
