export function validateObservatory(data){
 const errors=[];
 const problem=(condition,message)=>{if(!condition)errors.push(message);};
 const pair=(v,label)=>problem(v&&typeof v.en==='string'&&v.en.trim()&&typeof v.zh==='string'&&v.zh.trim(),`${label}: needs complete English and Chinese`);
 const date=(v)=>typeof v==='string'&&/^\d{4}-\d{2}(?:-\d{2})?$/.test(v)&&Number.isFinite(Date.parse(v));
 const url=(v)=>{try{return new URL(v).protocol==='https:';}catch{return false;}};
 problem(data?.schema_version===1,'schema_version: unsupported');problem(date(data?.snapshot),'snapshot: invalid date');problem(data?.updated===data?.snapshot,'updated: must match snapshot');pair(data?.selection,'selection');
 for(const key of ['layers','companies','models','sources','events','checkpoints','comparison']){const list=Array.isArray(data?.[key])?data[key]:[];problem(list.length>0,`${key}: required non-empty list`);const ids=list.map(x=>x?.id);problem(ids.every(id=>typeof id==='string'&&id.length>0),`${key}: missing ids`);problem(new Set(ids).size===ids.length,`${key}: duplicate ids`);}
 if(errors.length)return {ok:false,errors};
 const layers=new Set(data.layers.map(l=>l.id)),sources=new Set(data.sources.map(s=>s.id));
 for(const l of data.layers){pair(l.name,`layer ${l.id}`);pair(l.description,`layer ${l.id} description`);problem(data.companies.some(c=>c.layer===l.id),`layer ${l.id}: empty`);}
 for(const c of data.companies){pair(c.name,`company ${c.id}`);pair(c.role,`company ${c.id} role`);pair(c.city,`company ${c.id} city`);problem(layers.has(c.layer),`company ${c.id}: unknown layer`);pair(data.regions?.[c.country],`company ${c.id} country`);problem(Number.isFinite(c.lat)&&Math.abs(c.lat)<=90&&Number.isFinite(c.lon)&&Math.abs(c.lon)<=180,`company ${c.id}: invalid coordinates`);problem(url(c.url),`company ${c.id}: invalid official URL`);problem(date(c.checked),`company ${c.id}: missing check date`);problem(!c.logo||/^\/assets\/sectors\/logos\//.test(c.logo),`company ${c.id}: unsupported logo asset`);}
 for(const m of data.models){problem(typeof m.name==='string'&&m.name.length>0&&typeof m.configuration==='string'&&m.configuration.length>0,`model ${m.id}: name/configuration required`);pair(m.note,`model ${m.id} note`);problem(Number.isFinite(m.score)&&m.score>=0&&m.score<=100,`model ${m.id}: invalid score`);problem(Number.isFinite(m.cost)&&m.cost>=0,`model ${m.id}: invalid task cost`);for(const k of ['speed','latency'])problem(m[k]===null||Number.isFinite(m[k])&&m[k]>=0,`model ${m.id}: invalid ${k}`);problem([true,false,null].includes(m.open),`model ${m.id}: openness must remain explicit or unknown`);problem(sources.has(m.source),`model ${m.id}: missing source`);problem(Boolean(data.regions?.[m.country]),`model ${m.id}: unknown origin`);}
 for(const s of data.sources){pair(s.title,`source ${s.id}`);problem(url(s.url),`source ${s.id}: invalid URL`);problem(date(s.date)&&date(s.accessed),`source ${s.id}: invalid dates`);problem(['primary','research','independent','reported'].includes(s.kind),`source ${s.id}: unknown status`);problem(Date.parse(s.date)<=Date.parse(data.snapshot),`source ${s.id}: published after snapshot`);}
 let previous='';for(const ev of data.events){pair(ev.title,`event ${ev.id}`);pair(ev.body,`event ${ev.id} body`);problem(date(ev.date)&&ev.date>=previous&&Date.parse(ev.date)<=Date.parse(data.snapshot),`event ${ev.id}: invalid chronology`);previous=ev.date;problem(sources.has(ev.source),`event ${ev.id}: missing source`);}
 for(const c of data.checkpoints){pair(c.title,`checkpoint ${c.id}`);pair(c.status,`checkpoint ${c.id} status`);pair(c.body,`checkpoint ${c.id} evidence`);problem(sources.has(c.source),`checkpoint ${c.id}: missing evidence`);if(c.benchmark)problem(Number.isFinite(c.benchmark.value)&&c.benchmark.value>=0&&c.benchmark.value<=100&&date(c.benchmark.date),`checkpoint ${c.id}: invalid benchmark`);problem(!('percentComplete' in c),`checkpoint ${c.id}: benchmark percentage cannot become AGI completion`);}
 for(const c of data.comparison){pair(c.title,`comparison ${c.id}`);pair(c.unit,`comparison ${c.id} unit`);pair(c.note,`comparison ${c.id} limitation`);problem(sources.has(c.source),`comparison ${c.id}: missing source`);problem(Number.isFinite(c.us)&&Number.isFinite(c.cn)&&c.us>=0&&c.cn>=0,`comparison ${c.id}: invalid values`);}
 for(const row of data.battlegrounds||[]){for(const key of ['title','us','cn','note'])pair(row[key],`battleground ${row.id} ${key}`);problem(sources.has(row.source),`battleground ${row.id}: missing source`);}
 for(const f of data.anthropic?.facts||[]){problem(Number.isFinite(f.value)&&f.value>=0,`finance ${f.id}: invalid value`);problem(sources.has(f.source)&&typeof f.period==='string'&&f.period.length>0&&['official','reported'].includes(f.status),`finance ${f.id}: needs period, source and status`);}
 if(data.research){
 const r=data.research;problem(date(r.asOf)&&r.asOf<=data.snapshot,'research: invalid measurement date');
 for(const row of [...r.spending,...r.monetization]){pair(row.label,'research bar label');pair(row.note,'research bar basis');problem(Number.isFinite(row.value)&&row.value>=0&&row.value<=100,'research: invalid percentage');}
 for(const c of r.comparisons){pair(c.label,'research comparison label');pair(c.title,'research comparison title');pair(c.note,'research comparison basis');for(const v of c.values){pair(v.label,'research value label');problem(Number.isFinite(v.bar)&&v.bar>=0&&v.bar<=100,'research: invalid comparison bar');}}
 for(const c of r.cards){pair(c.title,'research card title');pair(c.body,'research card body');problem(sources.has(c.source),'research card: missing source');problem(['adoption','product','value'].includes(c.topic),'research card: unknown topic');}
 }
 return {ok:errors.length===0,errors};
}
