import React,{useEffect,useRef,useState} from 'react';
import {MagnifyingGlass,Plus,X,Check,ArrowDown,ArrowUp,ArrowUpRight,CaretDown} from '@phosphor-icons/react';
import {indices,stocks,initialWatchlist,formatPrice,signed,searchAssets} from './marketData.js';
import {MarketChart} from './MarketChart.jsx';
import {MarketClock} from './MarketClock.jsx';

const strings={
  zh:{overview:'市场总览',watch:'自选观察',learn:'学习',stories:'故事',more:'更多',search:'搜索股票代码',kicker:'WATCHLIST / 自选观察',headline:'把注意力，留给好公司。',lead:'在噪声中，寻找真正创造价值的企业。',closed:'休市 · 10月2日收盘',date:'2026年10月4日 / 墨尔本',sample:'设计示例 · 非实时',mine:'我的自选',add:'添加自选',company:'公司',price:'价格 USD',change:'今日涨跌',month:'近一月',focus:'观察焦点',chartNote:'示例走势 · USD',notice:'所有股价、涨跌幅及图表均为虚构数据，仅用于展示，不构成投资建议。',footer:'更少噪音 · 更好决策',modalTitle:'把下一家公司，放进自选。',modalLead:'搜索代码或名称，点击公司加入观察。',modalSearch:'搜索代码或公司，例如 AAPL / 苹果',added:'已在自选',join:'加入',noResults:'没有找到匹配的公司',tryAgain:'试试股票代码、中文或英文名称。',empty:'你的自选列表还空着',emptyLead:'点击上方“添加自选”，开始观察一家公司。',source:'示例数据',unit:'点',portfolio:'作品',industry:'AI 产业'},
  en:{overview:'Market overview',watch:'Watchlist',learn:'Learn',stories:'Stories',more:'More',search:'Search stocks',kicker:'WATCHLIST / COMPANY JOURNAL',headline:'Good companies, in focus.',lead:'Less noise. More attention to the companies creating value.',closed:'Market closed · Oct 2 close',date:'4 October 2026 / Melbourne',sample:'Design sample · Not live',mine:'My watchlist',add:'Add a stock',company:'Company',price:'Price USD',change:'Day change',month:'Past month',focus:'Research focus',chartNote:'Sample chart · USD',notice:'Fictional prices and charts for a design prototype. Not live market data or investment advice.',footer:'Less noise · Better decisions',modalTitle:'Your next company, in view.',modalLead:'Search a ticker or company, then add it to your list.',modalSearch:'Search a ticker or company, e.g. AAPL',added:'Watching',join:'Add',noResults:'No matching companies',tryAgain:'Try another ticker or company name.',empty:'Your watchlist is empty',emptyLead:'Use “Add a stock” above to start following a company.',source:'Sample data',unit:'points',portfolio:'Portfolio',industry:'AI industry'},
};

export function App({researchPanel=null}={}){
  const[locale,setLocale]=useState(()=>{const fixed=document.documentElement.dataset.afflatusLocale;return fixed==='en'||fixed==='zh'?fixed:(document.documentElement.lang.startsWith('zh')?'zh':'en');}),[selected,setSelected]=useState(stocks[3]),[period,setPeriod]=useState('M');
  const[watchlist,setWatchlist]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('afflatus:journal-watchlist:v1'));if(Array.isArray(saved))return [...new Set(saved.filter(sym=>stocks.some(asset=>asset.symbol===sym)))];}catch{}return initialWatchlist;}),[sort,setSort]=useState(null);
  const[modalOpen,setModalOpen]=useState(false),[modalQuery,setModalQuery]=useState(''),[toast,setToast]=useState('');
  const dialogRef=useRef(null),inputRef=useRef(null),addRef=useRef(null),workspaceRef=useRef(null),dragRef=useRef(false);
  const[chartStyle,setChartStyle]=useState('candles'),[split,setSplit]=useState(()=>{try{return Math.max(40,Math.min(68,Number(localStorage.getItem('afflatus:journal-split:v1'))||54));}catch{return 54;}});
  useEffect(()=>{try{localStorage.setItem('afflatus:journal-watchlist:v1',JSON.stringify(watchlist));}catch{}},[watchlist]);
  useEffect(()=>{try{localStorage.setItem('afflatus:journal-split:v1',String(split));}catch{}},[split]);
  const moveSplit=event=>{const rect=workspaceRef.current.getBoundingClientRect();setSplit(Math.max(40,Math.min(68,(event.clientX-rect.left)/rect.width*100)));};
  const english=locale==='en',t=strings[locale],isStock=stocks.includes(selected);
  let watching=watchlist.map(symbol=>stocks.find(asset=>asset.symbol===symbol)).filter(Boolean);
  if(sort)watching=[...watching].sort((a,b)=>sort==='desc'?b.pct-a.pct:a.pct-b.pct);
  const modalResults=searchAssets(modalQuery).filter(asset=>stocks.includes(asset));
  useEffect(()=>{
    document.documentElement.lang=english?'en':'zh-CN';document.title=english?'Market journal · AFFLATUS':'美股看板 · AFFLATUS';
    document.querySelectorAll('#afflatus-header [data-en],.pa-footer [data-en]').forEach(node=>{node.textContent=node.dataset[locale];});
    document.querySelectorAll('#afflatus-header [data-aria-en],.pa-footer [data-aria-en]').forEach(node=>node.setAttribute('aria-label',node.dataset[english?'ariaEn':'ariaZh']));
    document.querySelectorAll('#afflatus-header a[href],.pa-footer a[href]').forEach(a=>{const href=a.getAttribute('href');if(href.startsWith('/')||href.startsWith('https://feida.au/')){const path=href.replace('https://feida.au','').replace(/^\/(en|zh)(?=\/)/,'');a.href=`/${path==='/serial.html'?'zh':locale}${path}`;}});
    const language=document.querySelector('[data-header-language]');language.href=`/${english?'zh':'en'}/arena.html`;language.textContent=english?'中文':'EN';language.setAttribute('aria-label',english?'切换至中文':'Switch to English');
  },[english,locale]);
  useEffect(()=>{const button=document.querySelector('[data-header-language]');const change=event=>{if(['en','zh'].includes(document.documentElement.dataset.afflatusLocale))return;event.preventDefault();setLocale(value=>value==='zh'?'en':'zh');};button.addEventListener('click',change);return()=>button.removeEventListener('click',change);},[]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(timer);},[toast]);
  useEffect(()=>{if(modalOpen){dialogRef.current.showModal();inputRef.current.focus();}else if(dialogRef.current.open)dialogRef.current.close();},[modalOpen]);
  const selectAsset=asset=>{setSelected(asset);setPeriod(stocks.includes(asset)?'M':'D');};
  const openAdd=()=>{setModalQuery('');setModalOpen(true);};
  const closeAdd=()=>{setModalOpen(false);requestAnimationFrame(()=>addRef.current?.focus());};
  const addStock=asset=>{if(watchlist.includes(asset.symbol))return;setWatchlist(list=>[...list,asset.symbol]);setToast(english?`${asset.symbol} added to your watchlist`:`${asset.symbol} 已加入自选`);};
  const removeStock=asset=>{setWatchlist(list=>list.filter(symbol=>symbol!==asset.symbol));setToast(english?`${asset.symbol} removed`:`${asset.symbol} 已移出自选`);};
  const englishSectors={NVDA:'AI compute',MSFT:'Software & cloud',AVGO:'Custom silicon',MU:'Memory chips',TSM:'Semiconductor foundry',VRT:'Power & cooling',AAPL:'Consumer electronics',GOOGL:'AI & internet',AMZN:'Commerce & cloud',TSLA:'Electric vehicles',META:'Social & advertising',AMD:'Compute chips'};
  const symbolInfo=english?`${selected.symbol} · ${isStock?englishSectors[selected.symbol]:t.unit}`:`${selected.symbol} · ${selected.zh}${selected.sector?` · ${selected.sector}`:''}`;

  return <div className={`dashboard ${english?'is-english':''}`}>
    <a className="skip-link" href="#main-content">{english?'Skip to chart':'跳至主图表'}</a>
    <main id="main-content" className="main-content"><section className="intro" aria-labelledby="page-title"><div><p className="kicker">{t.kicker}</p><h1 id="page-title">{t.headline}</h1><p className="lead">{t.lead}</p></div><div className="market-status"><MarketClock english={english}/></div></section>
      <section className="index-strip" aria-label={english?'Market indices':'市场指数'}>{indices.map(asset=><button key={asset.symbol} className={`index-item ${selected.symbol===asset.symbol?'selected':''}`} aria-pressed={selected.symbol===asset.symbol} onClick={()=>selectAsset(asset)}><span className="index-name">{english?asset.name:asset.zh}</span><span className="index-quote"><strong>{formatPrice(asset.price)}</strong><span className="positive">{signed(asset.change)}<span>{signed(asset.pct)}%</span></span></span></button>)}</section>
      <section ref={workspaceRef} style={{'--stock-ratio':`${split/(100-split)}fr`,'--stock-share':split/100}} className="workspace" aria-label={english?'Market workspace':'行情工作台'}>
        <section className="detail-panel" aria-labelledby="detail-title"><h2 id="detail-title">{isStock?selected.short:(english?selected.name:selected.zh)}</h2><p className="symbol-info">{symbolInfo}</p><div className="detail-quote"><strong>{formatPrice(selected.price)}</strong><span className="currency">{isStock?'USD':t.unit}</span><span className={selected.pct>=0?'positive':'negative'}>{signed(selected.pct)}%</span></div><p className="quote-time">{english?'Oct 2, 16:00 ET':'10月2日 16:00 ET'}</p>
          <div className="periods" aria-label={english?'Chart period':'图表时间范围'}>{['D','M','3M','YTD','Y','MAX'].map(range=><button key={range} className={period===range?'selected':''} aria-pressed={period===range} onClick={()=>setPeriod(range)}>{range}</button>)}</div>
          <div className="chart-style-toggle" role="group" aria-label={english?'Chart style':'图表样式'}>{[['candles',english?'Candles':'烛形图'],['line',english?'Line':'折线图']].map(([style,label])=><button key={style} aria-pressed={chartStyle===style} className={chartStyle===style?'selected':''} onClick={()=>setChartStyle(style)}>{label}</button>)}</div><p className="chart-unit">{isStock?'USD':t.unit}</p><MarketChart key={`${selected.symbol}-${period}`} asset={selected} period={period} chartStyle={chartStyle} english={english} unit={isStock?'USD':t.unit}/><p className="chart-note">{isStock?t.chartNote:`${t.source} · ${t.unit}`}</p>
          <div className="research-note"><h3>{t.focus}</h3><p>{english?'Follow demand, supply constraints and company fundamentals.':selected.note}</p></div>
        </section>
        <div className="workspace-slider" role="separator" tabIndex={0} aria-orientation="vertical" aria-valuemin={40} aria-valuemax={68} aria-valuenow={Math.round(split)} aria-valuetext={english?`Stock ${Math.round(split)}%, watchlist ${100-Math.round(split)}%`:`个股 ${Math.round(split)}%，自选列表 ${100-Math.round(split)}%`} aria-label={english?'Resize stock and watchlist':'左右拖动调整个股与自选列表宽度'} onPointerDown={event=>{if(event.button!==0)return;dragRef.current=true;event.currentTarget.setPointerCapture(event.pointerId);event.currentTarget.focus();moveSplit(event);}} onPointerMove={event=>{if(dragRef.current)moveSplit(event);}} onPointerUp={()=>{dragRef.current=false;}} onPointerCancel={()=>{dragRef.current=false;}} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();setSplit(event.key==='Home'?40:event.key==='End'?68:Math.max(40,Math.min(68,split+(event.key==='ArrowLeft'?-2:2))));}}}><span aria-hidden="true">⋮</span></div>
        <aside className="watch-panel" aria-labelledby="watch-title"><div className="watch-heading"><h2 id="watch-title">{t.mine}</h2><button ref={addRef} className="primary-button" onClick={openAdd}><Plus size={18} weight="light" aria-hidden="true"/>{t.add}</button></div>
          <div className="table-head"><span>{t.company}</span><span>{t.price}</span><button className="sort-button" onClick={()=>setSort(value=>value==='desc'?'asc':'desc')} aria-label={english?`Sort daily change ${sort==='desc'?'ascending':'descending'}`:`按今日涨跌${sort==='desc'?'升序':'降序'}排列`}>{t.change}{sort==='asc'?<ArrowUp size={15} aria-hidden="true"/>:<ArrowDown size={15} aria-hidden="true"/>}</button><span>{t.month}</span></div>
          <div className="watch-rows">{watching.length?watching.map(asset=><div className={`watch-row ${selected.symbol===asset.symbol?'selected':''}`} key={asset.symbol}><button className="stock-select" onClick={()=>selectAsset(asset)} aria-pressed={selected.symbol===asset.symbol} aria-label={`${asset.symbol} ${asset.zh}, ${signed(asset.pct)}%`}><span className="stock-name"><b>{asset.symbol}</b><small>{asset.name}</small></span><strong className="stock-price">{formatPrice(asset.price)}</strong><span className={`stock-change ${asset.pct>=0?'positive':'negative'}`}>{signed(asset.pct)}%</span><MarketChart compact asset={asset}/></button><button className="remove-stock" onClick={()=>removeStock(asset)} aria-label={`${english?'Remove':'移除自选'} ${asset.symbol}`}><X size={12} aria-hidden="true"/></button></div>):<div className="empty-watch"><h3>{t.empty}</h3><p>{t.emptyLead}</p></div>}</div>
        </aside>
      </section>
      {researchPanel&&researchPanel(locale)}
    </main>
    <footer className="site-footer"><p>{researchPanel?(english?'The stock journal uses fictional design data. Daily market research shows separately sourced historical data. Not investment advice.':'个股观察区使用虚构设计数据；日线研究区使用注明来源的历史数据。非投资建议。'):t.notice}</p></footer>
    {toast&&<div className="toast" role="status"><Check size={18} aria-hidden="true"/>{toast}</div>}
    <dialog ref={dialogRef} className="stock-dialog" aria-labelledby="add-title" onKeyDownCapture={event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeAdd();}}} onCancel={event=>{event.preventDefault();closeAdd();}} onClick={event=>{if(event.target===event.currentTarget)closeAdd();}}><div className="dialog-content"><button className="dialog-close" onClick={closeAdd} aria-label={english?'Close':'关闭'}><X size={23} weight="light" aria-hidden="true"/></button><p className="kicker">AFFLATUS / WATCHLIST</p><h2 id="add-title">{t.modalTitle}</h2><p className="dialog-lead">{t.modalLead}</p><div className="dialog-search"><MagnifyingGlass size={21} weight="light" aria-hidden="true"/><input ref={inputRef} type="search" autoComplete="off" value={modalQuery} onChange={event=>setModalQuery(event.target.value)} placeholder={t.modalSearch} aria-label={t.modalSearch}/></div>
      <div className="dialog-results">{modalResults.length?modalResults.map(asset=><div className="dialog-stock" key={asset.symbol}><span><b>{asset.symbol}</b><small>{english?asset.name:`${asset.zh} · ${asset.name}`}</small></span><button disabled={watchlist.includes(asset.symbol)} className={watchlist.includes(asset.symbol)?'is-added':'add-stock'} onClick={()=>addStock(asset)}>{watchlist.includes(asset.symbol)?<Check size={16} aria-hidden="true"/>:<Plus size={16} aria-hidden="true"/>}{watchlist.includes(asset.symbol)?t.added:t.join}</button></div>):<div className="empty-search"><strong>{t.noResults}</strong><p>{t.tryAgain}</p></div>}</div>
    </div></dialog>
  </div>;
}
